//const 'name' = require('./"filename"')
const somar = require('./somar')
const subtrair = require('./subtrair')
const multiplicar = require('./multiplicar')
const dividir = require('./dividir')

console.log(somar(2,3))
console.log(subtrair(7,3))
console.log(multiplicar(5,3))
console.log(dividir(9,3))